max_jobs: 8

image:
  # - Visual Studio 2015
  - Visual Studio 2017

configuration:
  - Release
  # - Debug

platform:
  - x64

environment:
  matrix:
  - arch: Win64

matrix:
  allow_failures:
    - platform: x64
      configuration: Release

init:
  - set arch=
  - if "%arch%"=="Win64" ( set arch= Win64)
  - echo %arch%
  - echo %APPVEYOR_BUILD_WORKER_IMAGE%

before_build:
- cmd: |-
    cmake --version
    set BOOST_ROOT=C:\Libraries\boost_1_67_0
    set Boost_INCLUDE_DIRS=C:\Libraries\boost_1_67_0
    yarn

build_script:
  - yarn build_python --ci

# to disable automatic tests
test: off

# to disable deployment
deploy: off
