dist: trusty
language: node_js
node_js: "8"
sudo: required

services:
  - docker

matrix:
  include:
    - node_js: "8"
      language: node_js
      env: TEST=WASM

    - language: c++
      env: TEST=CPP

    - python: "3.6"
      language: python
      env: TEST=PYTHON
      cache: pip

cache:
  yarn: true
  directories:
    - node_modules
    - packages/perspective/node_modules
    - packages/perspective-examples/node_modules
    - packages/perspective-jupyterlab/node_modules
    - packages/perspective-viewer/node_modules
    - packages/perspective-viewer-highcharts/node_modules
    - packages/perspective-viewer-hypergrid/node_modules

env:
  global:
    - EM_USE_GLOBAL_CACHE=1


install:
  - yarn

script:
  - if [ "$TEST" = "WASM" ]; then yarn lint; fi
  - if [ "$TEST" = "WASM" ]; then PSP_DOCKER=1 yarn build; fi
  - if [ "$TEST" = "WASM" ]; then PSP_DOCKER=1 yarn test --quiet; fi
  - if [ "$TEST" = "CPP" ]; then PSP_DOCKER=1 yarn build_cpp; fi
  - if [ "$TEST" = "CPP" ]; then PSP_DOCKER=1 yarn test_cpp; fi
  - if [ "$TEST" = "PYTHON" ]; then PSP_DOCKER=1 yarn build_python; fi
  - if [ "$TEST" = "PYTHON" ]; then PSP_DOCKER=1 yarn lint_python; fi
  - if [ "$TEST" = "PYTHON" ]; then PSP_DOCKER=1 yarn test_python; fi
