dist: trusty

language: node_js

node_js:
  - "8"

cache:
  yarn: true
  directories:
    - node_modules
    - packages/perspective/node_modules
    - packages/perspective-examples/node_modules
    - packages/perspective-jupyterlab/node_modules
    - packages/perspective-viewer/node_modules
    - packages/perspective-viewer-highcharts/node_modules
    - packages/perspective-viewer-hypergrid/node_modules

env:
  global:
    - EM_USE_GLOBAL_CACHE=1

sudo: required

services:
  - docker

script:
  - npm run lint
  - PSP_DOCKER=1 npm run build
  - PSP_DOCKER=1 npm run test:build
  - npm run test:run_quiet