
dist: trusty

language: node_js

node_js:
  - "8"

env:
  global:
    - EM_USE_GLOBAL_CACHE=1

addons:
  apt:
    packages: &trusty_pocl_packages
      - libboost-all-dev

sudo: required

services:
  - docker

before_install:
  - mkdir boost_includes
  - cp -r /usr/include/boost boost_includes/
  - docker run -dit --name emscripten -v $(pwd):/src trzeci/emscripten:sdk-incoming-64bit bash

install:
  - npm install

script:
  - docker exec -it emscripten npm run travis_start
  - npm run travis_test
