trigger:
  tags:
    include:
    - '*'

jobs:
- job: 'Linux'
  pool:
    vmImage: 'ubuntu-16.04'

  strategy:
    matrix:
      Python27:
        python.version: '2.7'
        python_flag: '--python2'
        manylinux_flag: ''
        artifact_name: 'cp27-cp27m'
      Python27ManyLinux2010:
        python.version: '2.7'
        python_flag: '--python2'
        manylinux_flag: '--manylinux2010'
        artifact_name: 'cp27-cp27m-manylinux2010'
      Python37:
        python.version: '3.7'
        python_flag: ''
        manylinux_flag: ''
        artifact_name: 'cp37-cp37m'
      Python37ManyLinux2010:
        python.version: '3.7'
        python_flag: ''
        manylinux_flag: '--manylinux2010'
        artifact_name: 'cp37-cp37m-manylinux2010'
      Python37ManyLinux2014:
        python.version: '3.7'
        python_flag: ''
        manylinux_flag: '--manylinux2014'
        artifact_name: 'cp37-cp37m-manylinux2014'

  steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(python.version)'
        architecture: 'x64'

    - task: NodeTool@0
      inputs:
        versionSpec: '12.x'

    - bash: npm install -g yarn
      displayName: "Install Yarn"

    - bash: yarn
      displayName: 'Install Deps'

    - bash: yarn _wheel_python $(python_flag) $(manylinux_flag)
      displayName: 'Build wheel'
      env:
        PSP_DOCKER: 1

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(System.DefaultWorkingDirectory)/python/perspective/dist'
        artifactName: '$(artifact_name)'